# Generated by Django 5.2.12 on 2026-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentingsystem', '0002_booking_status_alter_booking_total_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
