# Generated by Django 5.2.12 on 2026-04-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentingsystem', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
    ]
