# Generated by Django 5.2.12 on 2026-04-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentingsystem', '0005_remove_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='vehicle'),
        ),
    ]
